version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
      KC_HEALTH_ENABLED: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
      interval: 15s
      timeout: 3s
      retries: 10
    command: ["start-dev", "--http-port", "8080", "--https-port", "7443"]
    ports:
      - "8200:8080"
    volumes:
      - ./keycloak/keycloak-discord:/opt/keycloak/providers